/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterGroomRouteImport } from './routes/register-groom'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppTaskResponsesRouteImport } from './routes/_app.task-responses'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProcurementRequestsRouteImport } from './routes/_app.procurement-requests'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppPaymentRequestsRouteImport } from './routes/_app.payment-requests'
import { Route as AppIdeasRouteImport } from './routes/_app.ideas'
import { Route as AppGroomsRouteImport } from './routes/_app.grooms'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunicationsRouteImport } from './routes/_app.communications'
import { Route as AppBrandRouteImport } from './routes/_app.brand'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppCommitteeTypeRouteImport } from './routes/_app.committee.$type'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminPermissionsRouteImport } from './routes/_app.admin.permissions'

const RegisterGroomRoute = RegisterGroomRouteImport.update({
  id: '/register-groom',
  path: '/register-groom',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskResponsesRoute = AppTaskResponsesRouteImport.update({
  id: '/task-responses',
  path: '/task-responses',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRequestsRoute = AppProcurementRequestsRouteImport.update({
  id: '/procurement-requests',
  path: '/procurement-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRequestsRoute = AppPaymentRequestsRouteImport.update({
  id: '/payment-requests',
  path: '/payment-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppGroomsRoute = AppGroomsRouteImport.update({
  id: '/grooms',
  path: '/grooms',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandRoute = AppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitteeTypeRoute = AppCommitteeTypeRouteImport.update({
  id: '/committee/$type',
  path: '/committee/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPermissionsRoute = AppAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/register-groom': typeof RegisterGroomRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/brand': typeof AppBrandRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/grooms': typeof AppGroomsRoute
  '/ideas': typeof AppIdeasRoute
  '/payment-requests': typeof AppPaymentRequestsRoute
  '/portal': typeof AppPortalRoute
  '/procurement-requests': typeof AppProcurementRequestsRoute
  '/reports': typeof AppReportsRoute
  '/task-responses': typeof AppTaskResponsesRoute
  '/team': typeof AppTeamRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/committee/$type': typeof AppCommitteeTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/register-groom': typeof RegisterGroomRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/brand': typeof AppBrandRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/grooms': typeof AppGroomsRoute
  '/ideas': typeof AppIdeasRoute
  '/payment-requests': typeof AppPaymentRequestsRoute
  '/portal': typeof AppPortalRoute
  '/procurement-requests': typeof AppProcurementRequestsRoute
  '/reports': typeof AppReportsRoute
  '/task-responses': typeof AppTaskResponsesRoute
  '/team': typeof AppTeamRoute
  '/admin/permissions': typeof AppAdminPermissionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/committee/$type': typeof AppCommitteeTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/register-groom': typeof RegisterGroomRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/brand': typeof AppBrandRoute
  '/_app/communications': typeof AppCommunicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/grooms': typeof AppGroomsRoute
  '/_app/ideas': typeof AppIdeasRoute
  '/_app/payment-requests': typeof AppPaymentRequestsRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/procurement-requests': typeof AppProcurementRequestsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/task-responses': typeof AppTaskResponsesRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/admin/permissions': typeof AppAdminPermissionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/committee/$type': typeof AppCommitteeTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/register-groom'
    | '/admin'
    | '/brand'
    | '/communications'
    | '/dashboard'
    | '/finance'
    | '/grooms'
    | '/ideas'
    | '/payment-requests'
    | '/portal'
    | '/procurement-requests'
    | '/reports'
    | '/task-responses'
    | '/team'
    | '/admin/permissions'
    | '/admin/users'
    | '/committee/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/register-groom'
    | '/admin'
    | '/brand'
    | '/communications'
    | '/dashboard'
    | '/finance'
    | '/grooms'
    | '/ideas'
    | '/payment-requests'
    | '/portal'
    | '/procurement-requests'
    | '/reports'
    | '/task-responses'
    | '/team'
    | '/admin/permissions'
    | '/admin/users'
    | '/committee/$type'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/pending'
    | '/register-groom'
    | '/_app/admin'
    | '/_app/brand'
    | '/_app/communications'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/grooms'
    | '/_app/ideas'
    | '/_app/payment-requests'
    | '/_app/portal'
    | '/_app/procurement-requests'
    | '/_app/reports'
    | '/_app/task-responses'
    | '/_app/team'
    | '/_app/admin/permissions'
    | '/_app/admin/users'
    | '/_app/committee/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  RegisterGroomRoute: typeof RegisterGroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-groom': {
      id: '/register-groom'
      path: '/register-groom'
      fullPath: '/register-groom'
      preLoaderRoute: typeof RegisterGroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/task-responses': {
      id: '/_app/task-responses'
      path: '/task-responses'
      fullPath: '/task-responses'
      preLoaderRoute: typeof AppTaskResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/procurement-requests': {
      id: '/_app/procurement-requests'
      path: '/procurement-requests'
      fullPath: '/procurement-requests'
      preLoaderRoute: typeof AppProcurementRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment-requests': {
      id: '/_app/payment-requests'
      path: '/payment-requests'
      fullPath: '/payment-requests'
      preLoaderRoute: typeof AppPaymentRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideas': {
      id: '/_app/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grooms': {
      id: '/_app/grooms'
      path: '/grooms'
      fullPath: '/grooms'
      preLoaderRoute: typeof AppGroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand': {
      id: '/_app/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AppBrandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/committee/$type': {
      id: '/_app/committee/$type'
      path: '/committee/$type'
      fullPath: '/committee/$type'
      preLoaderRoute: typeof AppCommitteeTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/permissions': {
      id: '/_app/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AppAdminPermissionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminPermissionsRoute: typeof AppAdminPermissionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminPermissionsRoute: AppAdminPermissionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBrandRoute: typeof AppBrandRoute
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGroomsRoute: typeof AppGroomsRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppPaymentRequestsRoute: typeof AppPaymentRequestsRoute
  AppPortalRoute: typeof AppPortalRoute
  AppProcurementRequestsRoute: typeof AppProcurementRequestsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTaskResponsesRoute: typeof AppTaskResponsesRoute
  AppTeamRoute: typeof AppTeamRoute
  AppCommitteeTypeRoute: typeof AppCommitteeTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBrandRoute: AppBrandRoute,
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGroomsRoute: AppGroomsRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppPaymentRequestsRoute: AppPaymentRequestsRoute,
  AppPortalRoute: AppPortalRoute,
  AppProcurementRequestsRoute: AppProcurementRequestsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTaskResponsesRoute: AppTaskResponsesRoute,
  AppTeamRoute: AppTeamRoute,
  AppCommitteeTypeRoute: AppCommitteeTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  RegisterGroomRoute: RegisterGroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
