/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPaymentRequestsRouteImport } from './routes/_app.payment-requests'
import { Route as AppIdeasRouteImport } from './routes/_app.ideas'
import { Route as AppGroomsRouteImport } from './routes/_app.grooms'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiAdminCreateMemberRouteImport } from './routes/api.admin.create-member'
import { Route as AppCommitteeTypeRouteImport } from './routes/_app.committee.$type'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentRequestsRoute = AppPaymentRequestsRouteImport.update({
  id: '/payment-requests',
  path: '/payment-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppGroomsRoute = AppGroomsRouteImport.update({
  id: '/grooms',
  path: '/grooms',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminCreateMemberRoute = ApiAdminCreateMemberRouteImport.update({
  id: '/api/admin/create-member',
  path: '/api/admin/create-member',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommitteeTypeRoute = AppCommitteeTypeRouteImport.update({
  id: '/committee/$type',
  path: '/committee/$type',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/grooms': typeof AppGroomsRoute
  '/ideas': typeof AppIdeasRoute
  '/payment-requests': typeof AppPaymentRequestsRoute
  '/reports': typeof AppReportsRoute
  '/team': typeof AppTeamRoute
  '/committee/$type': typeof AppCommitteeTypeRoute
  '/api/admin/create-member': typeof ApiAdminCreateMemberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/finance': typeof AppFinanceRoute
  '/grooms': typeof AppGroomsRoute
  '/ideas': typeof AppIdeasRoute
  '/payment-requests': typeof AppPaymentRequestsRoute
  '/reports': typeof AppReportsRoute
  '/team': typeof AppTeamRoute
  '/committee/$type': typeof AppCommitteeTypeRoute
  '/api/admin/create-member': typeof ApiAdminCreateMemberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/grooms': typeof AppGroomsRoute
  '/_app/ideas': typeof AppIdeasRoute
  '/_app/payment-requests': typeof AppPaymentRequestsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/committee/$type': typeof AppCommitteeTypeRoute
  '/api/admin/create-member': typeof ApiAdminCreateMemberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pending'
    | '/admin'
    | '/dashboard'
    | '/finance'
    | '/grooms'
    | '/ideas'
    | '/payment-requests'
    | '/reports'
    | '/team'
    | '/committee/$type'
    | '/api/admin/create-member'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pending'
    | '/admin'
    | '/dashboard'
    | '/finance'
    | '/grooms'
    | '/ideas'
    | '/payment-requests'
    | '/reports'
    | '/team'
    | '/committee/$type'
    | '/api/admin/create-member'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/pending'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/finance'
    | '/_app/grooms'
    | '/_app/ideas'
    | '/_app/payment-requests'
    | '/_app/reports'
    | '/_app/team'
    | '/_app/committee/$type'
    | '/api/admin/create-member'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  ApiAdminCreateMemberRoute: typeof ApiAdminCreateMemberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment-requests': {
      id: '/_app/payment-requests'
      path: '/payment-requests'
      fullPath: '/payment-requests'
      preLoaderRoute: typeof AppPaymentRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideas': {
      id: '/_app/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grooms': {
      id: '/_app/grooms'
      path: '/grooms'
      fullPath: '/grooms'
      preLoaderRoute: typeof AppGroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin/create-member': {
      id: '/api/admin/create-member'
      path: '/api/admin/create-member'
      fullPath: '/api/admin/create-member'
      preLoaderRoute: typeof ApiAdminCreateMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/committee/$type': {
      id: '/_app/committee/$type'
      path: '/committee/$type'
      fullPath: '/committee/$type'
      preLoaderRoute: typeof AppCommitteeTypeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGroomsRoute: typeof AppGroomsRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppPaymentRequestsRoute: typeof AppPaymentRequestsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppCommitteeTypeRoute: typeof AppCommitteeTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGroomsRoute: AppGroomsRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppPaymentRequestsRoute: AppPaymentRequestsRoute,
  AppReportsRoute: AppReportsRoute,
  AppTeamRoute: AppTeamRoute,
  AppCommitteeTypeRoute: AppCommitteeTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  ApiAdminCreateMemberRoute: ApiAdminCreateMemberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
