ALTER TABLE public.grooms
  ADD COLUMN IF NOT EXISTS cards_men INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS cards_women INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS cards_printed BOOLEAN NOT NULL DEFAULT false;